spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

jwt:
  secret: 66CI67KoMuqzvOygnOynhO2WieyekOykgOyasCbsi6DtmJXsnoXri4jri6Q=
token:
  name:
    LoginToken: LoginToken

admin:
  username: admin